# Generated by Django 4.0.4 on 2022-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Place_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
