# Generated by Django 4.0.4 on 2022-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.TextField(choices=[('Female', 'F'), ('Male', 'M')], default='Male'),
        ),
    ]
