# Generated by Django 4.0.4 on 2022-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(default=1, upload_to='user/'),
            preserve_default=False,
        ),
    ]
