# Generated by Django 4.0.4 on 2022-05-04 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TravelPlan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplanreq',
            old_name='travel_plan_id',
            new_name='travel_plan_idd',
        ),
        migrations.AlterUniqueTogether(
            name='travelplanreq',
            unique_together={('tour_leader', 'travel_plan_idd')},
        ),
    ]
