# Generated by Django 4.0.4 on 2022-05-06 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TravelPlan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='confirmed_tour_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='plan_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
