# Generated by Django 4.0.4 on 2022-05-04 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TravelPlan', '0002_rename_travel_plan_id_travelplanreq_travel_plan_idd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplanreq',
            old_name='travel_plan_idd',
            new_name='travel_plan_id',
        ),
        migrations.AlterUniqueTogether(
            name='travelplanreq',
            unique_together={('tour_leader', 'travel_plan_id')},
        ),
    ]
