# Generated by Django 4.0.4 on 2022-04-21 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='confirmed_users',
            field=models.ManyToManyField(related_name='confirmed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='pending_users',
            field=models.ManyToManyField(related_name='pending_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
