# Generated by Django 4.0.4 on 2022-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='tour',
            name='residence',
            field=models.TextField(choices=[('HT', 'Hotel'), ('S', 'Suite'), ('HS', 'House'), ('V', 'Villa'), ('N', 'None')], default='N'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='has_transportation',
            field=models.TextField(choices=[('C', 'Car'), ('B', 'Bus'), ('MB', 'Minibus'), ('V', 'Van'), ('N', 'None')], default='N'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_capacity',
            field=models.IntegerField(),
        ),
    ]
